language: scala
sudo: true
scala:
- 2.11.6
jdk:
- oraclejdk8
install: true
notifications:
  slack:
    rooms:
      secure: pU/8C95WBR6ohGKswwd0M+Y9wVK6D2gmozlea8DChvv7CG6nJ+RxKcWWER+GUuX12fnZsFRiy0oZrRp41uy1BNcTZUESio8rurxYsZD1ok8TsupXbU0NDt1/lDnN23AzM3rfiWhgZZdaKNP+BE2nwusFe+ZN7Oq5rKgvYXMS3Hn08BOc01JwhrQ8rz8+zmxsdnleO65qppruRyNiwxezlAr8mKi3P2e/NjSJfBtJpnwPlfSVm/IJZzSp+ImZnpqia0jIQKgQoXCYqyfNx6q3gMZobRs+/NIui2vzk8Eh/j1dTrctqFG1+OdHFXnFwQsULDDOKABCrBi+CSqyJogHD5fOoy6whP8zTUqv2GHAOHHfwwZoUo5gv8tBAT2lTL3wRyZCGxP8fe0JR53SgrNeay0+UIma/86GCF3u2YnqSmP3EvSaKGHI99peax9V+Y/Mc316BiOqEMtHmNfHXiCRGRWH6jOf/kbJdMG9CvSpsQplReAjgh7gvPjO0AaXKGryPyMRPqWK17qNIhHagYGoE6p2uHHCkkg3cGfhE5fzvTfRFX0gET4+Rnikxp3rqZ3yZyGetlVIjPdQJbSiFWXSe3002fhLjHQdepfHCmN3TLD1arqxVCdCYP7z02g50LPtcA7mXrXmVEOnC4aXZqcbhdBfWJcpoe2RufsOMe8CQgE=