// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostList.proto

package services.dataAccess.proto;

public final class PostListProto {
  private PostListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.dataAccess.proto.PostList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    java.util.List<services.dataAccess.proto.PostProto.Post> 
        getPostsList();
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    services.dataAccess.proto.PostProto.Post getPosts(int index);
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    int getPostsCount();
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    java.util.List<? extends services.dataAccess.proto.PostProto.PostOrBuilder> 
        getPostsOrBuilderList();
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    services.dataAccess.proto.PostProto.PostOrBuilder getPostsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code services.dataAccess.proto.PostList}
   */
  public  static final class PostList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.dataAccess.proto.PostList)
      PostListOrBuilder {
    // Use PostList.newBuilder() to construct.
    private PostList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostList() {
      posts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PostList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                posts_ = new java.util.ArrayList<services.dataAccess.proto.PostProto.Post>();
                mutable_bitField0_ |= 0x00000001;
              }
              posts_.add(
                  input.readMessage(services.dataAccess.proto.PostProto.Post.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          posts_ = java.util.Collections.unmodifiableList(posts_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return services.dataAccess.proto.PostListProto.internal_static_services_dataAccess_proto_PostList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return services.dataAccess.proto.PostListProto.internal_static_services_dataAccess_proto_PostList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              services.dataAccess.proto.PostListProto.PostList.class, services.dataAccess.proto.PostListProto.PostList.Builder.class);
    }

    public static final int POSTS_FIELD_NUMBER = 1;
    private java.util.List<services.dataAccess.proto.PostProto.Post> posts_;
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    public java.util.List<services.dataAccess.proto.PostProto.Post> getPostsList() {
      return posts_;
    }
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    public java.util.List<? extends services.dataAccess.proto.PostProto.PostOrBuilder> 
        getPostsOrBuilderList() {
      return posts_;
    }
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    public int getPostsCount() {
      return posts_.size();
    }
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    public services.dataAccess.proto.PostProto.Post getPosts(int index) {
      return posts_.get(index);
    }
    /**
     * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
     */
    public services.dataAccess.proto.PostProto.PostOrBuilder getPostsOrBuilder(
        int index) {
      return posts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < posts_.size(); i++) {
        output.writeMessage(1, posts_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < posts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, posts_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof services.dataAccess.proto.PostListProto.PostList)) {
        return super.equals(obj);
      }
      services.dataAccess.proto.PostListProto.PostList other = (services.dataAccess.proto.PostListProto.PostList) obj;

      boolean result = true;
      result = result && getPostsList()
          .equals(other.getPostsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPostsCount() > 0) {
        hash = (37 * hash) + POSTS_FIELD_NUMBER;
        hash = (53 * hash) + getPostsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostListProto.PostList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(services.dataAccess.proto.PostListProto.PostList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.dataAccess.proto.PostList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.dataAccess.proto.PostList)
        services.dataAccess.proto.PostListProto.PostListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return services.dataAccess.proto.PostListProto.internal_static_services_dataAccess_proto_PostList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return services.dataAccess.proto.PostListProto.internal_static_services_dataAccess_proto_PostList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                services.dataAccess.proto.PostListProto.PostList.class, services.dataAccess.proto.PostListProto.PostList.Builder.class);
      }

      // Construct using services.dataAccess.proto.PostListProto.PostList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPostsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (postsBuilder_ == null) {
          posts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          postsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return services.dataAccess.proto.PostListProto.internal_static_services_dataAccess_proto_PostList_descriptor;
      }

      public services.dataAccess.proto.PostListProto.PostList getDefaultInstanceForType() {
        return services.dataAccess.proto.PostListProto.PostList.getDefaultInstance();
      }

      public services.dataAccess.proto.PostListProto.PostList build() {
        services.dataAccess.proto.PostListProto.PostList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public services.dataAccess.proto.PostListProto.PostList buildPartial() {
        services.dataAccess.proto.PostListProto.PostList result = new services.dataAccess.proto.PostListProto.PostList(this);
        int from_bitField0_ = bitField0_;
        if (postsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            posts_ = java.util.Collections.unmodifiableList(posts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.posts_ = posts_;
        } else {
          result.posts_ = postsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof services.dataAccess.proto.PostListProto.PostList) {
          return mergeFrom((services.dataAccess.proto.PostListProto.PostList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(services.dataAccess.proto.PostListProto.PostList other) {
        if (other == services.dataAccess.proto.PostListProto.PostList.getDefaultInstance()) return this;
        if (postsBuilder_ == null) {
          if (!other.posts_.isEmpty()) {
            if (posts_.isEmpty()) {
              posts_ = other.posts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePostsIsMutable();
              posts_.addAll(other.posts_);
            }
            onChanged();
          }
        } else {
          if (!other.posts_.isEmpty()) {
            if (postsBuilder_.isEmpty()) {
              postsBuilder_.dispose();
              postsBuilder_ = null;
              posts_ = other.posts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              postsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPostsFieldBuilder() : null;
            } else {
              postsBuilder_.addAllMessages(other.posts_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        services.dataAccess.proto.PostListProto.PostList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (services.dataAccess.proto.PostListProto.PostList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<services.dataAccess.proto.PostProto.Post> posts_ =
        java.util.Collections.emptyList();
      private void ensurePostsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          posts_ = new java.util.ArrayList<services.dataAccess.proto.PostProto.Post>(posts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          services.dataAccess.proto.PostProto.Post, services.dataAccess.proto.PostProto.Post.Builder, services.dataAccess.proto.PostProto.PostOrBuilder> postsBuilder_;

      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public java.util.List<services.dataAccess.proto.PostProto.Post> getPostsList() {
        if (postsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(posts_);
        } else {
          return postsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public int getPostsCount() {
        if (postsBuilder_ == null) {
          return posts_.size();
        } else {
          return postsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public services.dataAccess.proto.PostProto.Post getPosts(int index) {
        if (postsBuilder_ == null) {
          return posts_.get(index);
        } else {
          return postsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder setPosts(
          int index, services.dataAccess.proto.PostProto.Post value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.set(index, value);
          onChanged();
        } else {
          postsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder setPosts(
          int index, services.dataAccess.proto.PostProto.Post.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.set(index, builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder addPosts(services.dataAccess.proto.PostProto.Post value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.add(value);
          onChanged();
        } else {
          postsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder addPosts(
          int index, services.dataAccess.proto.PostProto.Post value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.add(index, value);
          onChanged();
        } else {
          postsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder addPosts(
          services.dataAccess.proto.PostProto.Post.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.add(builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder addPosts(
          int index, services.dataAccess.proto.PostProto.Post.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.add(index, builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder addAllPosts(
          java.lang.Iterable<? extends services.dataAccess.proto.PostProto.Post> values) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, posts_);
          onChanged();
        } else {
          postsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder clearPosts() {
        if (postsBuilder_ == null) {
          posts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          postsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public Builder removePosts(int index) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.remove(index);
          onChanged();
        } else {
          postsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public services.dataAccess.proto.PostProto.Post.Builder getPostsBuilder(
          int index) {
        return getPostsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public services.dataAccess.proto.PostProto.PostOrBuilder getPostsOrBuilder(
          int index) {
        if (postsBuilder_ == null) {
          return posts_.get(index);  } else {
          return postsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public java.util.List<? extends services.dataAccess.proto.PostProto.PostOrBuilder> 
           getPostsOrBuilderList() {
        if (postsBuilder_ != null) {
          return postsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(posts_);
        }
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public services.dataAccess.proto.PostProto.Post.Builder addPostsBuilder() {
        return getPostsFieldBuilder().addBuilder(
            services.dataAccess.proto.PostProto.Post.getDefaultInstance());
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public services.dataAccess.proto.PostProto.Post.Builder addPostsBuilder(
          int index) {
        return getPostsFieldBuilder().addBuilder(
            index, services.dataAccess.proto.PostProto.Post.getDefaultInstance());
      }
      /**
       * <code>repeated .services.dataAccess.proto.Post posts = 1;</code>
       */
      public java.util.List<services.dataAccess.proto.PostProto.Post.Builder> 
           getPostsBuilderList() {
        return getPostsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          services.dataAccess.proto.PostProto.Post, services.dataAccess.proto.PostProto.Post.Builder, services.dataAccess.proto.PostProto.PostOrBuilder> 
          getPostsFieldBuilder() {
        if (postsBuilder_ == null) {
          postsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              services.dataAccess.proto.PostProto.Post, services.dataAccess.proto.PostProto.Post.Builder, services.dataAccess.proto.PostProto.PostOrBuilder>(
                  posts_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          posts_ = null;
        }
        return postsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:services.dataAccess.proto.PostList)
    }

    // @@protoc_insertion_point(class_scope:services.dataAccess.proto.PostList)
    private static final services.dataAccess.proto.PostListProto.PostList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new services.dataAccess.proto.PostListProto.PostList();
    }

    public static services.dataAccess.proto.PostListProto.PostList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostList>
        PARSER = new com.google.protobuf.AbstractParser<PostList>() {
      public PostList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PostList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostList> getParserForType() {
      return PARSER;
    }

    public services.dataAccess.proto.PostListProto.PostList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_dataAccess_proto_PostList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_dataAccess_proto_PostList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PostList.proto\022\031services.dataAccess.pr" +
      "oto\032\nPost.proto\":\n\010PostList\022.\n\005posts\030\001 \003" +
      "(\0132\037.services.dataAccess.proto.PostB*\n\031s" +
      "ervices.dataAccess.protoB\rPostListProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          services.dataAccess.proto.PostProto.getDescriptor(),
        }, assigner);
    internal_static_services_dataAccess_proto_PostList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_dataAccess_proto_PostList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_dataAccess_proto_PostList_descriptor,
        new java.lang.String[] { "Posts", });
    services.dataAccess.proto.PostProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
