// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Post.proto

package services.dataAccess.proto;

public final class PostProto {
  private PostProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.dataAccess.proto.Post)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string timestamp = 2;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>optional string timestamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>repeated string source = 3;</code>
     */
    java.util.List<java.lang.String>
        getSourceList();
    /**
     * <code>repeated string source = 3;</code>
     */
    int getSourceCount();
    /**
     * <code>repeated string source = 3;</code>
     */
    java.lang.String getSource(int index);
    /**
     * <code>repeated string source = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes(int index);

    /**
     * <code>repeated string source_link = 4;</code>
     */
    java.util.List<java.lang.String>
        getSourceLinkList();
    /**
     * <code>repeated string source_link = 4;</code>
     */
    int getSourceLinkCount();
    /**
     * <code>repeated string source_link = 4;</code>
     */
    java.lang.String getSourceLink(int index);
    /**
     * <code>repeated string source_link = 4;</code>
     */
    com.google.protobuf.ByteString
        getSourceLinkBytes(int index);

    /**
     * <code>optional int32 popularity_score = 5;</code>
     */
    int getPopularityScore();

    /**
     * <code>optional int32 popularity_velocity = 6;</code>
     */
    int getPopularityVelocity();

    /**
     * <code>optional int32 num_comments = 7;</code>
     */
    int getNumComments();

    /**
     * <code>optional int32 num_shares = 8;</code>
     */
    int getNumShares();

    /**
     * <code>optional int32 num_likes = 9;</code>
     */
    int getNumLikes();

    /**
     * <code>repeated string hashtag = 10;</code>
     */
    java.util.List<java.lang.String>
        getHashtagList();
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    int getHashtagCount();
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    java.lang.String getHashtag(int index);
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    com.google.protobuf.ByteString
        getHashtagBytes(int index);

    /**
     * <code>repeated string text = 11;</code>
     */
    java.util.List<java.lang.String>
        getTextList();
    /**
     * <code>repeated string text = 11;</code>
     */
    int getTextCount();
    /**
     * <code>repeated string text = 11;</code>
     */
    java.lang.String getText(int index);
    /**
     * <code>repeated string text = 11;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes(int index);

    /**
     * <code>repeated string img_link = 12;</code>
     */
    java.util.List<java.lang.String>
        getImgLinkList();
    /**
     * <code>repeated string img_link = 12;</code>
     */
    int getImgLinkCount();
    /**
     * <code>repeated string img_link = 12;</code>
     */
    java.lang.String getImgLink(int index);
    /**
     * <code>repeated string img_link = 12;</code>
     */
    com.google.protobuf.ByteString
        getImgLinkBytes(int index);

    /**
     * <code>repeated string ext_link = 13;</code>
     */
    java.util.List<java.lang.String>
        getExtLinkList();
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    int getExtLinkCount();
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    java.lang.String getExtLink(int index);
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    com.google.protobuf.ByteString
        getExtLinkBytes(int index);
  }
  /**
   * Protobuf type {@code services.dataAccess.proto.Post}
   */
  public  static final class Post extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.dataAccess.proto.Post)
      PostOrBuilder {
    // Use Post.newBuilder() to construct.
    private Post(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Post() {
      id_ = "";
      timestamp_ = "";
      source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sourceLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      popularityScore_ = 0;
      popularityVelocity_ = 0;
      numComments_ = 0;
      numShares_ = 0;
      numLikes_ = 0;
      hashtag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      imgLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      extLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Post(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                source_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              source_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                sourceLink_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              sourceLink_.add(s);
              break;
            }
            case 40: {

              popularityScore_ = input.readInt32();
              break;
            }
            case 48: {

              popularityVelocity_ = input.readInt32();
              break;
            }
            case 56: {

              numComments_ = input.readInt32();
              break;
            }
            case 64: {

              numShares_ = input.readInt32();
              break;
            }
            case 72: {

              numLikes_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                hashtag_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              hashtag_.add(s);
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                text_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000400;
              }
              text_.add(s);
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
                imgLink_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000800;
              }
              imgLink_.add(s);
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
                extLink_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00001000;
              }
              extLink_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          source_ = source_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          sourceLink_ = sourceLink_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          hashtag_ = hashtag_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          text_ = text_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
          imgLink_ = imgLink_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
          extLink_ = extLink_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return services.dataAccess.proto.PostProto.internal_static_services_dataAccess_proto_Post_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return services.dataAccess.proto.PostProto.internal_static_services_dataAccess_proto_Post_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              services.dataAccess.proto.PostProto.Post.class, services.dataAccess.proto.PostProto.Post.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>optional string timestamp = 2;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>optional string timestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList source_;
    /**
     * <code>repeated string source = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSourceList() {
      return source_;
    }
    /**
     * <code>repeated string source = 3;</code>
     */
    public int getSourceCount() {
      return source_.size();
    }
    /**
     * <code>repeated string source = 3;</code>
     */
    public java.lang.String getSource(int index) {
      return source_.get(index);
    }
    /**
     * <code>repeated string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes(int index) {
      return source_.getByteString(index);
    }

    public static final int SOURCE_LINK_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList sourceLink_;
    /**
     * <code>repeated string source_link = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSourceLinkList() {
      return sourceLink_;
    }
    /**
     * <code>repeated string source_link = 4;</code>
     */
    public int getSourceLinkCount() {
      return sourceLink_.size();
    }
    /**
     * <code>repeated string source_link = 4;</code>
     */
    public java.lang.String getSourceLink(int index) {
      return sourceLink_.get(index);
    }
    /**
     * <code>repeated string source_link = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourceLinkBytes(int index) {
      return sourceLink_.getByteString(index);
    }

    public static final int POPULARITY_SCORE_FIELD_NUMBER = 5;
    private int popularityScore_;
    /**
     * <code>optional int32 popularity_score = 5;</code>
     */
    public int getPopularityScore() {
      return popularityScore_;
    }

    public static final int POPULARITY_VELOCITY_FIELD_NUMBER = 6;
    private int popularityVelocity_;
    /**
     * <code>optional int32 popularity_velocity = 6;</code>
     */
    public int getPopularityVelocity() {
      return popularityVelocity_;
    }

    public static final int NUM_COMMENTS_FIELD_NUMBER = 7;
    private int numComments_;
    /**
     * <code>optional int32 num_comments = 7;</code>
     */
    public int getNumComments() {
      return numComments_;
    }

    public static final int NUM_SHARES_FIELD_NUMBER = 8;
    private int numShares_;
    /**
     * <code>optional int32 num_shares = 8;</code>
     */
    public int getNumShares() {
      return numShares_;
    }

    public static final int NUM_LIKES_FIELD_NUMBER = 9;
    private int numLikes_;
    /**
     * <code>optional int32 num_likes = 9;</code>
     */
    public int getNumLikes() {
      return numLikes_;
    }

    public static final int HASHTAG_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList hashtag_;
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHashtagList() {
      return hashtag_;
    }
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    public int getHashtagCount() {
      return hashtag_.size();
    }
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    public java.lang.String getHashtag(int index) {
      return hashtag_.get(index);
    }
    /**
     * <code>repeated string hashtag = 10;</code>
     */
    public com.google.protobuf.ByteString
        getHashtagBytes(int index) {
      return hashtag_.getByteString(index);
    }

    public static final int TEXT_FIELD_NUMBER = 11;
    private com.google.protobuf.LazyStringList text_;
    /**
     * <code>repeated string text = 11;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_;
    }
    /**
     * <code>repeated string text = 11;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 11;</code>
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }

    public static final int IMG_LINK_FIELD_NUMBER = 12;
    private com.google.protobuf.LazyStringList imgLink_;
    /**
     * <code>repeated string img_link = 12;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getImgLinkList() {
      return imgLink_;
    }
    /**
     * <code>repeated string img_link = 12;</code>
     */
    public int getImgLinkCount() {
      return imgLink_.size();
    }
    /**
     * <code>repeated string img_link = 12;</code>
     */
    public java.lang.String getImgLink(int index) {
      return imgLink_.get(index);
    }
    /**
     * <code>repeated string img_link = 12;</code>
     */
    public com.google.protobuf.ByteString
        getImgLinkBytes(int index) {
      return imgLink_.getByteString(index);
    }

    public static final int EXT_LINK_FIELD_NUMBER = 13;
    private com.google.protobuf.LazyStringList extLink_;
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getExtLinkList() {
      return extLink_;
    }
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    public int getExtLinkCount() {
      return extLink_.size();
    }
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    public java.lang.String getExtLink(int index) {
      return extLink_.get(index);
    }
    /**
     * <code>repeated string ext_link = 13;</code>
     */
    public com.google.protobuf.ByteString
        getExtLinkBytes(int index) {
      return extLink_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      for (int i = 0; i < source_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, source_.getRaw(i));
      }
      for (int i = 0; i < sourceLink_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceLink_.getRaw(i));
      }
      if (popularityScore_ != 0) {
        output.writeInt32(5, popularityScore_);
      }
      if (popularityVelocity_ != 0) {
        output.writeInt32(6, popularityVelocity_);
      }
      if (numComments_ != 0) {
        output.writeInt32(7, numComments_);
      }
      if (numShares_ != 0) {
        output.writeInt32(8, numShares_);
      }
      if (numLikes_ != 0) {
        output.writeInt32(9, numLikes_);
      }
      for (int i = 0; i < hashtag_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, hashtag_.getRaw(i));
      }
      for (int i = 0; i < text_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, text_.getRaw(i));
      }
      for (int i = 0; i < imgLink_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, imgLink_.getRaw(i));
      }
      for (int i = 0; i < extLink_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, extLink_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < source_.size(); i++) {
          dataSize += computeStringSizeNoTag(source_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSourceList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sourceLink_.size(); i++) {
          dataSize += computeStringSizeNoTag(sourceLink_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSourceLinkList().size();
      }
      if (popularityScore_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, popularityScore_);
      }
      if (popularityVelocity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, popularityVelocity_);
      }
      if (numComments_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, numComments_);
      }
      if (numShares_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, numShares_);
      }
      if (numLikes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, numLikes_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hashtag_.size(); i++) {
          dataSize += computeStringSizeNoTag(hashtag_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHashtagList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < text_.size(); i++) {
          dataSize += computeStringSizeNoTag(text_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTextList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < imgLink_.size(); i++) {
          dataSize += computeStringSizeNoTag(imgLink_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImgLinkList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < extLink_.size(); i++) {
          dataSize += computeStringSizeNoTag(extLink_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getExtLinkList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof services.dataAccess.proto.PostProto.Post)) {
        return super.equals(obj);
      }
      services.dataAccess.proto.PostProto.Post other = (services.dataAccess.proto.PostProto.Post) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getSourceList()
          .equals(other.getSourceList());
      result = result && getSourceLinkList()
          .equals(other.getSourceLinkList());
      result = result && (getPopularityScore()
          == other.getPopularityScore());
      result = result && (getPopularityVelocity()
          == other.getPopularityVelocity());
      result = result && (getNumComments()
          == other.getNumComments());
      result = result && (getNumShares()
          == other.getNumShares());
      result = result && (getNumLikes()
          == other.getNumLikes());
      result = result && getHashtagList()
          .equals(other.getHashtagList());
      result = result && getTextList()
          .equals(other.getTextList());
      result = result && getImgLinkList()
          .equals(other.getImgLinkList());
      result = result && getExtLinkList()
          .equals(other.getExtLinkList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      if (getSourceCount() > 0) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceList().hashCode();
      }
      if (getSourceLinkCount() > 0) {
        hash = (37 * hash) + SOURCE_LINK_FIELD_NUMBER;
        hash = (53 * hash) + getSourceLinkList().hashCode();
      }
      hash = (37 * hash) + POPULARITY_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getPopularityScore();
      hash = (37 * hash) + POPULARITY_VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + getPopularityVelocity();
      hash = (37 * hash) + NUM_COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getNumComments();
      hash = (37 * hash) + NUM_SHARES_FIELD_NUMBER;
      hash = (53 * hash) + getNumShares();
      hash = (37 * hash) + NUM_LIKES_FIELD_NUMBER;
      hash = (53 * hash) + getNumLikes();
      if (getHashtagCount() > 0) {
        hash = (37 * hash) + HASHTAG_FIELD_NUMBER;
        hash = (53 * hash) + getHashtagList().hashCode();
      }
      if (getTextCount() > 0) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getTextList().hashCode();
      }
      if (getImgLinkCount() > 0) {
        hash = (37 * hash) + IMG_LINK_FIELD_NUMBER;
        hash = (53 * hash) + getImgLinkList().hashCode();
      }
      if (getExtLinkCount() > 0) {
        hash = (37 * hash) + EXT_LINK_FIELD_NUMBER;
        hash = (53 * hash) + getExtLinkList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static services.dataAccess.proto.PostProto.Post parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.dataAccess.proto.PostProto.Post parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostProto.Post parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.dataAccess.proto.PostProto.Post parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(services.dataAccess.proto.PostProto.Post prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.dataAccess.proto.Post}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.dataAccess.proto.Post)
        services.dataAccess.proto.PostProto.PostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return services.dataAccess.proto.PostProto.internal_static_services_dataAccess_proto_Post_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return services.dataAccess.proto.PostProto.internal_static_services_dataAccess_proto_Post_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                services.dataAccess.proto.PostProto.Post.class, services.dataAccess.proto.PostProto.Post.Builder.class);
      }

      // Construct using services.dataAccess.proto.PostProto.Post.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        timestamp_ = "";

        source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        sourceLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        popularityScore_ = 0;

        popularityVelocity_ = 0;

        numComments_ = 0;

        numShares_ = 0;

        numLikes_ = 0;

        hashtag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        imgLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        extLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return services.dataAccess.proto.PostProto.internal_static_services_dataAccess_proto_Post_descriptor;
      }

      public services.dataAccess.proto.PostProto.Post getDefaultInstanceForType() {
        return services.dataAccess.proto.PostProto.Post.getDefaultInstance();
      }

      public services.dataAccess.proto.PostProto.Post build() {
        services.dataAccess.proto.PostProto.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public services.dataAccess.proto.PostProto.Post buildPartial() {
        services.dataAccess.proto.PostProto.Post result = new services.dataAccess.proto.PostProto.Post(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.timestamp_ = timestamp_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          source_ = source_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.source_ = source_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          sourceLink_ = sourceLink_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.sourceLink_ = sourceLink_;
        result.popularityScore_ = popularityScore_;
        result.popularityVelocity_ = popularityVelocity_;
        result.numComments_ = numComments_;
        result.numShares_ = numShares_;
        result.numLikes_ = numLikes_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          hashtag_ = hashtag_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.hashtag_ = hashtag_;
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          text_ = text_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.text_ = text_;
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          imgLink_ = imgLink_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.imgLink_ = imgLink_;
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          extLink_ = extLink_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.extLink_ = extLink_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof services.dataAccess.proto.PostProto.Post) {
          return mergeFrom((services.dataAccess.proto.PostProto.Post)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(services.dataAccess.proto.PostProto.Post other) {
        if (other == services.dataAccess.proto.PostProto.Post.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.source_.isEmpty()) {
          if (source_.isEmpty()) {
            source_ = other.source_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSourceIsMutable();
            source_.addAll(other.source_);
          }
          onChanged();
        }
        if (!other.sourceLink_.isEmpty()) {
          if (sourceLink_.isEmpty()) {
            sourceLink_ = other.sourceLink_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSourceLinkIsMutable();
            sourceLink_.addAll(other.sourceLink_);
          }
          onChanged();
        }
        if (other.getPopularityScore() != 0) {
          setPopularityScore(other.getPopularityScore());
        }
        if (other.getPopularityVelocity() != 0) {
          setPopularityVelocity(other.getPopularityVelocity());
        }
        if (other.getNumComments() != 0) {
          setNumComments(other.getNumComments());
        }
        if (other.getNumShares() != 0) {
          setNumShares(other.getNumShares());
        }
        if (other.getNumLikes() != 0) {
          setNumLikes(other.getNumLikes());
        }
        if (!other.hashtag_.isEmpty()) {
          if (hashtag_.isEmpty()) {
            hashtag_ = other.hashtag_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureHashtagIsMutable();
            hashtag_.addAll(other.hashtag_);
          }
          onChanged();
        }
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
        if (!other.imgLink_.isEmpty()) {
          if (imgLink_.isEmpty()) {
            imgLink_ = other.imgLink_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureImgLinkIsMutable();
            imgLink_.addAll(other.imgLink_);
          }
          onChanged();
        }
        if (!other.extLink_.isEmpty()) {
          if (extLink_.isEmpty()) {
            extLink_ = other.extLink_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureExtLinkIsMutable();
            extLink_.addAll(other.extLink_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        services.dataAccess.proto.PostProto.Post parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (services.dataAccess.proto.PostProto.Post) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>optional string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timestamp = 2;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 2;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSourceIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          source_ = new com.google.protobuf.LazyStringArrayList(source_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSourceList() {
        return source_.getUnmodifiableView();
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public int getSourceCount() {
        return source_.size();
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public java.lang.String getSource(int index) {
        return source_.get(index);
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes(int index) {
        return source_.getByteString(index);
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public Builder setSource(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIsMutable();
        source_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public Builder addSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIsMutable();
        source_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public Builder addAllSource(
          java.lang.Iterable<java.lang.String> values) {
        ensureSourceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, source_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public Builder clearSource() {
        source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source = 3;</code>
       */
      public Builder addSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSourceIsMutable();
        source_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList sourceLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSourceLinkIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          sourceLink_ = new com.google.protobuf.LazyStringArrayList(sourceLink_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSourceLinkList() {
        return sourceLink_.getUnmodifiableView();
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public int getSourceLinkCount() {
        return sourceLink_.size();
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public java.lang.String getSourceLink(int index) {
        return sourceLink_.get(index);
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSourceLinkBytes(int index) {
        return sourceLink_.getByteString(index);
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public Builder setSourceLink(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceLinkIsMutable();
        sourceLink_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public Builder addSourceLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceLinkIsMutable();
        sourceLink_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public Builder addAllSourceLink(
          java.lang.Iterable<java.lang.String> values) {
        ensureSourceLinkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sourceLink_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public Builder clearSourceLink() {
        sourceLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string source_link = 4;</code>
       */
      public Builder addSourceLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSourceLinkIsMutable();
        sourceLink_.add(value);
        onChanged();
        return this;
      }

      private int popularityScore_ ;
      /**
       * <code>optional int32 popularity_score = 5;</code>
       */
      public int getPopularityScore() {
        return popularityScore_;
      }
      /**
       * <code>optional int32 popularity_score = 5;</code>
       */
      public Builder setPopularityScore(int value) {
        
        popularityScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 popularity_score = 5;</code>
       */
      public Builder clearPopularityScore() {
        
        popularityScore_ = 0;
        onChanged();
        return this;
      }

      private int popularityVelocity_ ;
      /**
       * <code>optional int32 popularity_velocity = 6;</code>
       */
      public int getPopularityVelocity() {
        return popularityVelocity_;
      }
      /**
       * <code>optional int32 popularity_velocity = 6;</code>
       */
      public Builder setPopularityVelocity(int value) {
        
        popularityVelocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 popularity_velocity = 6;</code>
       */
      public Builder clearPopularityVelocity() {
        
        popularityVelocity_ = 0;
        onChanged();
        return this;
      }

      private int numComments_ ;
      /**
       * <code>optional int32 num_comments = 7;</code>
       */
      public int getNumComments() {
        return numComments_;
      }
      /**
       * <code>optional int32 num_comments = 7;</code>
       */
      public Builder setNumComments(int value) {
        
        numComments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num_comments = 7;</code>
       */
      public Builder clearNumComments() {
        
        numComments_ = 0;
        onChanged();
        return this;
      }

      private int numShares_ ;
      /**
       * <code>optional int32 num_shares = 8;</code>
       */
      public int getNumShares() {
        return numShares_;
      }
      /**
       * <code>optional int32 num_shares = 8;</code>
       */
      public Builder setNumShares(int value) {
        
        numShares_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num_shares = 8;</code>
       */
      public Builder clearNumShares() {
        
        numShares_ = 0;
        onChanged();
        return this;
      }

      private int numLikes_ ;
      /**
       * <code>optional int32 num_likes = 9;</code>
       */
      public int getNumLikes() {
        return numLikes_;
      }
      /**
       * <code>optional int32 num_likes = 9;</code>
       */
      public Builder setNumLikes(int value) {
        
        numLikes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num_likes = 9;</code>
       */
      public Builder clearNumLikes() {
        
        numLikes_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hashtag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHashtagIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          hashtag_ = new com.google.protobuf.LazyStringArrayList(hashtag_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHashtagList() {
        return hashtag_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public int getHashtagCount() {
        return hashtag_.size();
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public java.lang.String getHashtag(int index) {
        return hashtag_.get(index);
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public com.google.protobuf.ByteString
          getHashtagBytes(int index) {
        return hashtag_.getByteString(index);
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public Builder setHashtag(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashtagIsMutable();
        hashtag_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public Builder addHashtag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHashtagIsMutable();
        hashtag_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public Builder addAllHashtag(
          java.lang.Iterable<java.lang.String> values) {
        ensureHashtagIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hashtag_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public Builder clearHashtag() {
        hashtag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hashtag = 10;</code>
       */
      public Builder addHashtagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHashtagIsMutable();
        hashtag_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTextIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          text_ = new com.google.protobuf.LazyStringArrayList(text_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTextList() {
        return text_.getUnmodifiableView();
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public int getTextCount() {
        return text_.size();
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public java.lang.String getText(int index) {
        return text_.get(index);
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes(int index) {
        return text_.getByteString(index);
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public Builder setText(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public Builder addText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public Builder addAllText(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, text_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public Builder clearText() {
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 11;</code>
       */
      public Builder addTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList imgLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImgLinkIsMutable() {
        if (!((bitField0_ & 0x00000800) == 0x00000800)) {
          imgLink_ = new com.google.protobuf.LazyStringArrayList(imgLink_);
          bitField0_ |= 0x00000800;
         }
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getImgLinkList() {
        return imgLink_.getUnmodifiableView();
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public int getImgLinkCount() {
        return imgLink_.size();
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public java.lang.String getImgLink(int index) {
        return imgLink_.get(index);
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public com.google.protobuf.ByteString
          getImgLinkBytes(int index) {
        return imgLink_.getByteString(index);
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public Builder setImgLink(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgLinkIsMutable();
        imgLink_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public Builder addImgLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImgLinkIsMutable();
        imgLink_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public Builder addAllImgLink(
          java.lang.Iterable<java.lang.String> values) {
        ensureImgLinkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, imgLink_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public Builder clearImgLink() {
        imgLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string img_link = 12;</code>
       */
      public Builder addImgLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImgLinkIsMutable();
        imgLink_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList extLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureExtLinkIsMutable() {
        if (!((bitField0_ & 0x00001000) == 0x00001000)) {
          extLink_ = new com.google.protobuf.LazyStringArrayList(extLink_);
          bitField0_ |= 0x00001000;
         }
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getExtLinkList() {
        return extLink_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public int getExtLinkCount() {
        return extLink_.size();
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public java.lang.String getExtLink(int index) {
        return extLink_.get(index);
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public com.google.protobuf.ByteString
          getExtLinkBytes(int index) {
        return extLink_.getByteString(index);
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public Builder setExtLink(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExtLinkIsMutable();
        extLink_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public Builder addExtLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExtLinkIsMutable();
        extLink_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public Builder addAllExtLink(
          java.lang.Iterable<java.lang.String> values) {
        ensureExtLinkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extLink_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public Builder clearExtLink() {
        extLink_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ext_link = 13;</code>
       */
      public Builder addExtLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureExtLinkIsMutable();
        extLink_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:services.dataAccess.proto.Post)
    }

    // @@protoc_insertion_point(class_scope:services.dataAccess.proto.Post)
    private static final services.dataAccess.proto.PostProto.Post DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new services.dataAccess.proto.PostProto.Post();
    }

    public static services.dataAccess.proto.PostProto.Post getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Post>
        PARSER = new com.google.protobuf.AbstractParser<Post>() {
      public Post parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Post(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Post> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Post> getParserForType() {
      return PARSER;
    }

    public services.dataAccess.proto.PostProto.Post getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_dataAccess_proto_Post_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_dataAccess_proto_Post_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nPost.proto\022\031services.dataAccess.proto\"" +
      "\201\002\n\004Post\022\n\n\002id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\t\022" +
      "\016\n\006source\030\003 \003(\t\022\023\n\013source_link\030\004 \003(\t\022\030\n\020" +
      "popularity_score\030\005 \001(\005\022\033\n\023popularity_vel" +
      "ocity\030\006 \001(\005\022\024\n\014num_comments\030\007 \001(\005\022\022\n\nnum" +
      "_shares\030\010 \001(\005\022\021\n\tnum_likes\030\t \001(\005\022\017\n\007hash" +
      "tag\030\n \003(\t\022\014\n\004text\030\013 \003(\t\022\020\n\010img_link\030\014 \003(" +
      "\t\022\020\n\010ext_link\030\r \003(\tB&\n\031services.dataAcce" +
      "ss.protoB\tPostProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_services_dataAccess_proto_Post_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_dataAccess_proto_Post_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_dataAccess_proto_Post_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Source", "SourceLink", "PopularityScore", "PopularityVelocity", "NumComments", "NumShares", "NumLikes", "Hashtag", "Text", "ImgLink", "ExtLink", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
